### ISSUE TITLE
Failed to build workspace Specta with scheme Specta-iOS

### ISSUE THREAD

**Issue by numbbuaa** [erichoracek/Motif-FLXView#1]
After running command 'carthage update', I have met an error below:
"A shell task failed with exit code 70:
xcodebuild: error: Failed to build workspace Specta with scheme Specta-iOS.
    Reason: The run destination iPad 2 is not valid for Running the scheme 'Specta-iOS'."
If I need change some configure to fix this error?

**Comment by erichoracek** [comment]
@numbbuaa do you have the iOS 7.1 simulator installed? I've seen a similar issues when that occurs.

**Comment by numbbuaa** [comment]
@erichoracek I use Xcode 6.3.2 with iOS 7.1 simulator installed.

**Comment by erichoracek** [comment]
Hmm—I think you're experiencing similar issues to https://github.com/Carthage/Carthage/issues/417

Have you tried without the 7.1 simulator installed?

**Comment by erichoracek** [comment]
Closing since this is a carthage bug, feel free to reopen if necessary
